# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb4f3fc40b6fdd22fd90d58806981d3f79094e50cc6618540e1847c75e46ece1526f87895f72e6b9c513ec874170952f94d37dd1361b79b0dcfd45b2cd643e4

test:
  secret_key_base: 157dd897935bb6b52776c164ba7be6d1d08f5ec244bd83cc331a7a6b2fcb959a8450cc5beec60d32f6a45850a100ca2083eddced49ae1d97c454e71dbcd23909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
